name: example
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  collection: ^1.16.0

  tw591_video_play:
    path: ../../tw591_video_play

dependency_overrides:
  
  webview_flutter:
    version: ^4.2.0+2
    hosted:
      name: webview_flutter
      url: http://192.168.8.75:4000/
  webview_flutter_android:
    version: ^3.7.0+2
    hosted:
      name: webview_flutter_android
      url: http://192.168.8.75:4000/
  webview_flutter_platform_interface:
    version: ^2.3.0+2
    hosted:
      name: webview_flutter_platform_interface
      url: http://192.168.8.75:4000/
  webview_flutter_wkwebview:
    version: ^3.4.3+2
    hosted:
      name: webview_flutter_wkwebview
      url: http://192.168.8.75:4000/

  # tw591_base_features:
  #   path: ../../tw591_base_features

  url_launcher: 6.1.11
  package_info_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
